### ISSUE TITLE
 .DS 파일 및 필요없는 모듈삭제 요망

### ISSUE THREAD

**Issue by kseymin** [Chars4785/MovieC#1]
.DS파일 과   node모듈에 필요없는 것들을 
.ignore파일에 추가해서 삭제시켜야할것같습니다

관련 정보 링크입니다.
간단설명:
https://help.github.com/en/articles/ignoring-files
매뉴얼:
https://git-scm.com/docs/gitignore

**Comment by Chars4785** [comment]
오케이
